name: Latched Media
favicon: null
layout_spectrum: 0.35329463123343885
typography_spectrum: 0.8313632486388087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5372823670040816
  lightness: 0.8984713603276759
  saturation: 0.8558808153029531
  rhythmicContrast: 0.7592178010381758
purpose: []
