name: Latched Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85448
title: Latched Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8cbdc'
    - '#1f3243'
    - '#d8ebfc'
    - '#495c6d'
    - '#6d8091'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
